sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm install --global npm
  - npm install --global yarn
before_script:
  - yarn install
script:
  - yarn run coverage
after_success:
  - yarn run report:coverage
  - yarn run build
  - yarn run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
